export default [
  {
    ignores: ["node_modules/", "dist/", "build/", "public/"],
  },
  {
    languageOptions: {
      ecmaVersion: "latest",
      sourceType: "module",
      globals: {
        window: "readonly",
        document: "readonly",
        console: "readonly",
        NavigatorCore: "readonly",
        fetch: "readonly",
        localStorage: "readonly",
        sessionStorage: "readonly",
        URLSearchParams: "readonly",
        setTimeout: "readonly",
        setInterval: "readonly",
        clearTimeout: "readonly",
        clearInterval: "readonly",
        alert: "readonly",
        Timeless: "readonly",
        TimelessWeb: "readonly",
        ref: "readonly",
        computed: "readonly",
        isRef: "readonly",
        isComponent: "readonly",
        classnames: "readonly",
        Show: "readonly",
        For: "readonly",
        Match: "readonly",
        View: "readonly",
        Txt: "readonly",
        DangerouslyInnerHTML: "readonly",
        // content
        Flex: "readonly",
        ScrollView: "readonly",
        Tabs: "readonly",
        Button: "readonly",
        DropdownMenu: "readonly",
        Progress: "readonly",
        // form
        Input: "readonly",
        Checkbox: "readonly",
        Select: "readonly",
        Switch: "readonly",
        Slider: "readonly",
        // dialog
        Popover: "readonly",
        Modal: "readonly",
        Presence: "readonly",
        Portal: "readonly",
      },
    },
    rules: {
      "no-unused-vars": "warn",
      "no-undef": "warn",
      semi: ["warn", "always"],
      indent: [
        "warn",
        2,
        { ignoreComments: true, ignoredNodes: ["TemplateLiteral > *"] },
      ],
    },
  },
];
